# Define the name of the GitHub Actions workflow
name: mhdTest

# Specify when the workflow should run. In this case, the workflow will run on every push to the 'main' branch.
on:
  push:
    branches:
      - "master"

# Define the jobs that make up the workflow. Each job runs in a fresh instance of the virtual environment.
jobs:
  # Define the 'test' job. This job runs tests for the project.
  test:
    # Specify the type of runner to use for this job. In this case, an Ubuntu runner is used.
    runs-on: ubuntu-latest

    # Define the steps that make up the 'test' job.
    steps:
      # Check out the repository's code.
      - name: get code
        uses: actions/checkout@v4

      # Set up the Node.js environment with the specified version.
      - name: setup node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18
      # Install the dependencies for the project.
      - name: Install dependencies
        run: npm install
      # Run the tests.
      - name: test
        run: npm test

  # Define the 'build' job. This job builds the project and deploys it.
  build:
    # Specify the type of runner to use for this job. In this case, an Ubuntu runner is used.
    runs-on: ubuntu-latest
    needs: test
    # Define the steps that make up the 'build' job.
    steps:
      # Check out the repository's code.
      - name: get code
        uses: actions/checkout@v4

      # Set up the Node.js environment with the specified version.
      - name: setup node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18

      # Install the dependencies for the project.
      - name: Install dependencies
        run: npm install

      # Build the project.
      - name: build
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "dist-files"
          path: "dist"
      # Deploy the project.
      - name: Deploy
        run: echo "deploying"
